from enum import Enum


class AccountActivities(Enum):
    ACCOUNT_ENROLMENT = "ACCOUNT_ENROLMENT"
    ACCOUNT_CHANGE = "ACCOUNT_CHANGE"
    ACCOUNT_AUTHENTICATION = "ACCOUNT_AUTHENTICATION"
    ACCOUNT_REQUEST = "ACCOUNT_REQUEST"
